Repository ember-tooling/prettier-plugin-ember-template-tag, pull requests merged in 2023-12, with the labels that each got.

#180 Remove @glimmer/syntax dependency
  package.json
  pnpm-lock.yaml
Labels: dependencies

#158 Upgrade Prettier to 3.1 (including relevant docs updates)
  README.md
  examples/package.json
  package.json
  pnpm-lock.yaml
Labels: dependencies

#181 Upgrade eslint and eslint plugins (not including typescript-eslint)
  package.json
  pnpm-lock.yaml
Labels: dependencies

#185 Remove ember-cli-htmlbars dependency
  package.json
  pnpm-lock.yaml
Labels: dependencies

#195 More content-tag cleanup
  examples/package.json
  src/parse/index.ts
  src/parse/preprocess.ts
  src/parse/whitespace.ts
  src/print/index.ts
  src/types/glimmer.ts
Labels: enhancement

#207 Upgrade dev dependencies
  package.json
  pnpm-lock.yaml
  tests/package.json
Labels: dependencies

#209 Upgrade vite to v5, vitest to v1
  package.json
  pnpm-lock.yaml
  tests/package.json
  tests/unit-tests/__snapshots__/format.test.ts.snap
  tests/unit-tests/ambiguous/__snapshots__/arrow-parens-avoid.test.ts.snap
  tests/unit-tests/ambiguous/__snapshots__/index.test.ts.snap
  tests/unit-tests/ambiguous/__snapshots__/semi-false.test.ts.snap
  tests/unit-tests/config/__snapshots__/semi-false.test.ts.snap
  tests/unit-tests/config/__snapshots__/template-export-default.test.ts.snap
  tests/unit-tests/config/__snapshots__/template-single-quote.test.ts.snap
Labels: dependencies

#210 Upgrade Prettier to 3.1.1
  @types/prettier/plugins/estree.d.ts
  examples/package.json
  package.json
  pnpm-lock.yaml
Labels: dependencies

#211 Upgrade content-tag
  package.json
  pnpm-lock.yaml
  src/parse/index.ts
  src/parse/preprocess.ts
  src/types/glimmer.ts
Labels: dependencies

#212 Fix bug where preceding {} was slurping up template
  src/parse/index.ts
  src/parse/preprocess.ts
  src/print/index.ts
  src/types/glimmer.ts
  tests/cases/gjs/preceded-by-object.gjs
  tests/unit-tests/__snapshots__/format.test.ts.snap
  tests/unit-tests/ambiguous/__snapshots__/index.test.ts.snap
  tests/unit-tests/ambiguous/__snapshots__/semi-false.test.ts.snap
  tests/unit-tests/config/__snapshots__/semi-false.test.ts.snap
  tests/unit-tests/config/__snapshots__/template-export-default.test.ts.snap
Labels: bug
